name: Build wheels

on:
 push:
  branches:
    - main
 workflow_call:

jobs:

 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Upload checkout
      uses: actions/upload-artifact@v4
      with:
        name: checkout
        path: .

 build-linux:
  needs: checkout
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v4
      with:
        name: checkout
        path: .
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
    - name: Download redis
      run: |
        wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        tar -xvzf redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        rm redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        mv redis-stack-server-7.2.0-v9 redis_stack_wheel/redis-stack-server
    - run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: List dir for sanity checking
      run: ls -R

    - name: Rename wheel
      run: |
        BUILD_TAG=$(date -u "+%Y%m%d%H%M")
        WHL_NAME="dist/redis_stack_wheel-0.1.0-${BUILD_TAG}-${{ matrix.abi_tag }}-manylinux_2_31_x86_64.whl"
        mv dist/redis_stack_wheel-0.1.0-py3-none-any.whl $WHL_NAME
        echo $WHL_NAME

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: distribution-linux
        path: dist/

 build-macos:
  needs: checkout
  runs-on: macOS-11
  strategy:
    matrix:
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v4
      with:
        name: checkout
        path: .
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
    - name: Download redis
      run: |
        wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        unzip -d redis-stack-server redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        rm redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        mv redis-stack-server redis_stack_wheel/redis-stack-server
    - run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: List dir for sanity checking
      run: ls -R

    - name: Rename wheel
      run: |
        BUILD_TAG=$(date -u "+%Y%m%d%H%M")
        WHL_NAME="dist/redis_stack_wheel-0.1.0-${BUILD_TAG}-${{ matrix.abi_tag }}-macosx_11_0_x86_64.whl"
        mv dist/redis_stack_wheel-0.1.0-py3-none-any.whl $WHL_NAME
        echo $WHL_NAME

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: distribution-macos
        path: dist/
