name: Build wheels

on:
 push:
  branches:
    - main
    - paulan/new_builds
 workflow_call:

jobs:

 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Upload checkout
      uses: actions/upload-artifact@v4
      with:
        name: checkout
        path: .

 build-linux:
  needs: checkout
  runs-on: ubuntu-latest
  strategy:
    matrix:
      our_version:
        - "0.1.4"
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v4
      with:
        name: checkout
        path: .
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
    - name: Download redis
      run: |
        wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        tar -xvzf redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        rm redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        mv redis-stack-server-7.2.0-v9 src/redis_stack_wheel/redis-stack-server
    - name: Overwrite server startup file
      run: cp overwrite/redis-stack-server src/redis_stack_wheel/redis-stack-server/bin/redis-stack-server
    - run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: List dir for sanity checking
      run: ls -R

    - name: Rename wheel
      run: |
        BUILD_TAG=$(date -u "+%Y%m%d%H%M")
        WHL_NAME="dist/redis_stack_wheel-${{ matrix.our_version }}-${BUILD_TAG}-${{ matrix.abi_tag }}-manylinux_2_31_x86_64.whl"
        mv dist/redis_stack_wheel-${{ matrix.our_version }}-py3-none-any.whl $WHL_NAME
        echo $WHL_NAME

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: distribution-linux-${{ matrix.python_version }}
        path: dist/

 build-macos-x64:
  needs: checkout
  runs-on: macOS-13
  strategy:
    matrix:
      our_version:
        - "0.1.4"
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v4
      with:
        name: checkout
        path: .
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer      

    - name: Show current version of Xcode
      run: xcodebuild -version
      
    - name: Download redis
      run: |
        wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        unzip -d redis-stack-server redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        rm redis-stack-server-7.2.0-v9.catalina.x86_64.zip
        mv redis-stack-server src/redis_stack_wheel/redis-stack-server
    - name: Overwrite server startup file
      run: cp overwrite/redis-stack-server src/redis_stack_wheel/redis-stack-server/bin/redis-stack-server
    - run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: List dir for sanity checking
      run: ls -R

    - name: Rename wheel
      run: |
        BUILD_TAG=$(date -u "+%Y%m%d%H%M")
        WHL_NAME="dist/redis_stack_wheel-${{ matrix.our_version }}-${BUILD_TAG}-${{ matrix.abi_tag }}-macosx_14_0_x86_64.whl"
        mv dist/redis_stack_wheel-${{ matrix.our_version }}-py3-none-any.whl $WHL_NAME
        echo $WHL_NAME

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: distribution-macos-x64-${{ matrix.python_version }}
        path: dist/
