name: Build wheels

on:
 push:
  branches:
    - main
 workflow_call:

jobs:

 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Upload checkout
      uses: actions/upload-artifact@v3
      with:
        name: checkout
        path: .

 download-redis:
  needs: checkout
  runs-on: ubuntu-latest
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v3
      with:
        name: checkout
        path: .
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9.16'
        cache: 'pip'
    - name: Download redis
      run: |
        wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        tar -xvzf redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        rm redis-stack-server-7.2.0-v9.focal.x86_64.tar.gz
        mv redis-stack-server-7.2.0-v9 redis_stack_wheel/redis-stack-server
    - run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: List dir for sanity checking
      run: ls -R
    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: dist/
